name: Test
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        fail: [true, false]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  next:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - if: needs.build.result != 'success'
        name: Fail the build
        run: exit 1
